### ISSUE TITLE
Docker containers are throwing error (missing dependence wirebox)

### ISSUE THREAD

**Issue by michaeldiederich** [cfwheels/cfwheels#1494]
Pulling cfwheels develop branch, `docker compose up` and the containers are starting
Accessing the lucee5 or lucee 6 tests:

URL: http://localhost:60006/wheels/testbox?format=json&sort=directory%20asc&db=mysql

Message | invalid component definition, can't find component [wirebox.system.ioc.Injector]
-- | --
Function | onApplicationStart
Component | Application
Stacktrace | The Error Occurred in/cfwheels-test-suite/public/Application.cfc: line 8280:81:    function onApplicationStart() {82:       wirebox = new wirebox.system.ioc.Injector("wheels.Wirebox");83:

Could you please check this dependence?

Thanks,

Michael

**Comment by bpamiri** [comment]
@michaeldiederich this should be resolved in the latest snapshot. The only Docker container I'm having problems with is the SQL Server container launching on a M4 Mac. It's on my list of items to look into but the MySQL, PostgreSQL, and H2 are all working.

**Comment by michaeldiederich** [comment]
Hi @bpamiri, i removed everything local, downloaded the branch ´develop´ and build docker by ´docker compose up´. I still get the same error. I also have a M4 Mac.

**Comment by bpamiri** [comment]
@michaeldiederich I have found that doing a docker compose up to launch all the containers takes a long time and is prone to failures. I suspect that it is because the individual containers load the same file structure and that can have some race conditions. 

So try this, do docker compose up testui. That should laundh a container that runs on port 3000 that will have the framework test runner. 

After you have that running and can access the UI, do a docker compose up lucee5 or docker compose up lucee6 to launch the Lucee container you want. With just the Lucee container running you can run the Lucee tests for H2 database since this doesn't require any other database container to run. 

If you want to test a particular database, launch the container for the DB you want. i.e. docker compose up mysql. Once that container is running you can run the additional test for the Lucee and DB combination.

Regardless of how many of the engines you launch the code is mapped into them so you could make changes in your code and it would be reflected in the Lucee or ACF containers.

Also keep in mind this is only needed if you need a development and testing environment to create a PR and submit code changes back to the project. Obviously I would welcome PRs with open arms but you don't need this environment for day to day development. 

Let me know if this helps or if I confused things even further.

**Comment by michaeldiederich** [comment]
Hi @bpamiri,

thanks for explanation, everything clear so far. I did as you told me, but I still get the same error. I'm also not sure, where the wirebox folder should be - I just found the `wirebox.cfc`. From my point of view, this error has nothing todo with my docker environment or any race conditions at starting.

I want to check the latest lucee version with cfwheels and see I have some spare time to support you. But first, I want a stable environment for testing.
